### ISSUE TITLE
Not able to host the code on railway

### ISSUE THREAD

**Issue by NabhyaP** [FlafyDev/spotify-listen-together-server#1]
Hey so i wanted to get rid off heroku because of it limits so i decided to host on railway or any other host but the place where i am stuck now is that it asks me for a start command now in heroku when i went and saw the resources it only says npm start now i am only a py developer so idk how these thing works so it would be great if u told me what i have to put in the blank where it asks for me start command

**Comment by FlafyDev** [comment]
The start command should be `yarn run start`. But make sure you deploy the application after changing the start command.
I didn't know `railway.app` existed until just a few minutes ago so this is all very new to me, but I managed to force a deployment after adding an environment variable in the `Variables` tab under `Environment`. 

By the way, don't forget to add the `HOST_PASSWORD` and `MAX_DELAY` environment variables.

**Comment by NabhyaP** [comment]
Thx for the help btw i had already added the variables cus i saw them under the config vars in heroku
so i have them already

**Comment by NabhyaP** [comment]
![image_2022-02-12_005405](https://user-images.githubusercontent.com/83863829/153656324-6d8d2a8c-154b-4c2e-b853-c24a7ec38396.png)
Hey so i changed the start command to `yarn run start` but still this error is happening i have added a custom domain as `testforspotify.com`

**Comment by NabhyaP** [comment]
I'll try reinstalling the project and then tell you

**Comment by FlafyDev** [comment]
> ![image_2022-02-12_005405](https://user-images.githubusercontent.com/83863829/153656324-6d8d2a8c-154b-4c2e-b853-c24a7ec38396.png) Hey so i changed the start command to `yarn run start` but still this error is happening i have added a custom domain as `testforspotify.com`

have you redeployed after changing the start command?

**Comment by NabhyaP** [comment]
![image](https://user-images.githubusercontent.com/83863829/153656956-1c7c73fb-cef3-46a2-85da-ce6d2911d6ea.png)
i have to press this to do that right?

**Comment by NabhyaP** [comment]
cus im using railway.app for the first time myself

**Comment by FlafyDev** [comment]
> ![image](https://user-images.githubusercontent.com/83863829/153656956-1c7c73fb-cef3-46a2-85da-ce6d2911d6ea.png) i have to press this to do that right?

No, restarting doesn't redeploy. Reread my first comment, it explains how to do so.

**Comment by NabhyaP** [comment]
ok i figured it out
i had the singleton thing on bc of which i wasnt getting a new deploy button
so even after removing the exsisting deploy it wasnt redploying it
its working now thx
